### PR TITLE
PhpDoc fix

### PR DESCRIPTION
**Pull request by baptistecosta**

### CODE REVIEW

**Comment by GuillaumeBadi** [comment]
:+1: ! Thanks @baptistecosta

**Comment by baptistecosta** [comment]
Hi,

Thank you for taking a look at my pull request, could you also consider switching "Resources" class static property to constant?

Baptiste.

**Comment by GuillaumeBadi** [comment]
Thanks for your contribution. Why would it be necessary to make them constant ?

Guillaume.

**Comment by baptistecosta** [comment]
It's not necessary but it would prevent anyone from changing their values during the flow of the program. Also, we're using code sniffer in our society with Symfony coding standard and my IDE is complaining, have a look :
screenshot from 2016-04-04 16-09-54

**Comment by GuillaumeBadi** [comment]
Ok that is something I am going to work on ! I'll keep you up to date!

**Pull request merged**
