### PR TITLE
Fix guzzle ServerException uncaught

### PR DESCRIPTION
**Pull request by axi**
untested

### CODE REVIEW

**Comment by axi** [comment]
I tested it pointing to a local test url returning http 500 and error is caught

**Comment by GuillaumeBadi** [comment]
Cool! Looks good to me! Let me merge it, fix the tests if necessary, then release on packagist! i'll keep you up to date ! Thanks for your contribution!

**Comment by axi** [comment]
You're welcome

**Comment by GuillaumeBadi** [comment]
Released on Packagist! Have fun!

**Pull request merged**
